#!/bin/sh
# Splicing sub-seismograms into a whole seismogram
all:
	icc -w -o spli splice.cpp -lm
	./spli

# Note that above compile instructions are suitable for the icc compiler, and the compile instructions #for the gcc compiler are
#	gcc -w -o spli splice.cpp -lm
#	./spli
