#!/bin/sh
# Decomposing velocity and density models
all:
	icc -w -o spl split.cpp -lm
	./spl
	
# Note that above compile instructions are suitable for the icc compiler, and the compile instructions #for the gcc compiler are
#	gcc -w -o spl split.cpp -lm
#	./spl
